M48
; DRILL file KiCad 10.0.1 date 2026-06-06T15:03:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-06T15:03:36-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X120.0Y-61.0
X120.0Y-129.0
X208.0Y-61.0
X208.0Y-130.0
T2
X149.46Y-106.66
M30
